/*
 * RIXL API
 *
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[async_trait]
pub trait VideosApi: Send + Sync {

    /// DELETE /videos/{videoId}/delete
    ///
    /// Delete a video by its ID within a project
    async fn delete(&self,  params: DeleteParams ) -> Result<(), Error<DeleteError>>;

    /// DELETE /videos/{videoId}/audio-tracks/{trackId}
    ///
    /// Remove an additional audio track from a video using API key authentication
    async fn delete_audio_track(&self,  params: DeleteAudioTrackParams ) -> Result<models::AudioTrackDelete, Error<DeleteAudioTrackError>>;

    /// DELETE /videos/{videoId}/audio-tracks/language/{lang_code}
    ///
    /// Remove an audio track for a specific language using API key authentication
    async fn delete_audio_track_by_language(&self,  params: DeleteAudioTrackByLanguageParams ) -> Result<models::AudioTrackDelete, Error<DeleteAudioTrackByLanguageError>>;

    /// DELETE /videos/{videoId}/audio-tracks
    ///
    /// Remove all additional audio tracks from a video using API key authentication
    async fn delete_audio_tracks(&self,  params: DeleteAudioTracksParams ) -> Result<models::AudioTrackDelete, Error<DeleteAudioTracksError>>;

    /// DELETE /videos/{videoId}/chapters
    ///
    /// Remove all chapters from a video using API key authentication
    async fn delete_chapters(&self,  params: DeleteChaptersParams ) -> Result<models::UpdateChaptersResponse, Error<DeleteChaptersError>>;

    /// DELETE /videos/{videoId}/subtitles/{subtitleId}
    ///
    /// Remove a subtitle from a video using API key authentication
    async fn delete_subtitle(&self,  params: DeleteSubtitleParams ) -> Result<models::SubtitleDelete, Error<DeleteSubtitleError>>;

    /// DELETE /videos/{videoId}/subtitles/language/{lang_code}
    ///
    /// Remove a subtitle for a specific language using API key authentication
    async fn delete_subtitle_by_language(&self,  params: DeleteSubtitleByLanguageParams ) -> Result<models::SubtitleDelete, Error<DeleteSubtitleByLanguageError>>;

    /// DELETE /videos/{videoId}/subtitles
    ///
    /// Remove all subtitles from a video using API key authentication
    async fn delete_subtitles(&self,  params: DeleteSubtitlesParams ) -> Result<models::SubtitleDelete, Error<DeleteSubtitlesError>>;

    /// GET /videos/{videoId}
    ///
    /// Retrieve a video by its ID for a specific project.
    async fn get(&self,  params: GetParams ) -> Result<models::Video, Error<GetError>>;

    /// GET /videos
    ///
    /// Retrieve all videos for a specific project, with pagination and sorting.
    async fn list(&self,  params: ListParams ) -> Result<models::PaginationPaginatedResponseVideo, Error<ListError>>;

    /// GET /videos/languages
    ///
    /// Get list of supported languages for subtitles
    async fn list_languages(&self, ) -> Result<Vec<models::SubtitleLanguageResponse>, Error<ListLanguagesError>>;

    /// POST /videos/{videoId}/audio-tracks
    ///
    /// Replace all audio tracks with the provided ones using API key authentication
    async fn replace_audio_tracks(&self,  params: ReplaceAudioTracksParams ) -> Result<Vec<models::AudioTrack>, Error<ReplaceAudioTracksError>>;

    /// POST /videos/{videoId}/subtitles
    ///
    /// Replace all subtitles with the provided ones using API key authentication
    async fn replace_subtitles(&self,  params: ReplaceSubtitlesParams ) -> Result<Vec<models::Subtitle>, Error<ReplaceSubtitlesError>>;

    /// PUT /videos/{videoId}/audio-tracks/language/{lang_code}
    ///
    /// Add or replace an audio track for a specific language using API key authentication
    async fn update_audio_track_by_language(&self,  params: UpdateAudioTrackByLanguageParams ) -> Result<models::AudioTrack, Error<UpdateAudioTrackByLanguageError>>;

    /// PUT /videos/{videoId}/chapters
    ///
    /// Replace all chapters for a video (atomic PUT operation) using API key authentication
    async fn update_chapters(&self,  params: UpdateChaptersParams ) -> Result<models::UpdateChaptersResponse, Error<UpdateChaptersError>>;

    /// PUT /videos/{videoId}/subtitles/language/{lang_code}
    ///
    /// Add or replace a subtitle for a specific language using API key authentication
    async fn update_subtitle_by_language(&self,  params: UpdateSubtitleByLanguageParams ) -> Result<models::Subtitle, Error<UpdateSubtitleByLanguageError>>;

    /// PUT /videos/{videoId}/thumbnail
    ///
    /// Update the thumbnail image for an existing video using API key authentication
    async fn update_thumbnail(&self,  params: UpdateThumbnailParams ) -> Result<models::Video, Error<UpdateThumbnailError>>;

    /// POST /videos/upload/complete
    ///
    /// Mark a video upload as complete after successful upload to storage using API key authentication
    async fn upload_complete(&self,  params: UploadCompleteParams ) -> Result<models::Video, Error<UploadCompleteError>>;

    /// POST /videos/upload/init
    ///
    /// Initialize a video upload and get presigned URLs for video and poster using API key authentication
    async fn upload_init(&self,  params: UploadInitParams ) -> Result<models::VideoUploadInitResponse, Error<UploadInitError>>;
}

pub struct VideosApiClient {
    configuration: Arc<configuration::Configuration>
}

impl VideosApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}


/// struct for passing parameters to the method [`VideosApi::delete`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteParams {
    /// Video ID
    pub video_id: String
}

/// struct for passing parameters to the method [`VideosApi::delete_audio_track`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteAudioTrackParams {
    /// Video ID
    pub video_id: String,
    /// Audio Track ID
    pub track_id: String
}

/// struct for passing parameters to the method [`VideosApi::delete_audio_track_by_language`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteAudioTrackByLanguageParams {
    /// Video ID
    pub video_id: String,
    /// Language Code (BCP 47)
    pub lang_code: String
}

/// struct for passing parameters to the method [`VideosApi::delete_audio_tracks`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteAudioTracksParams {
    /// Video ID
    pub video_id: String
}

/// struct for passing parameters to the method [`VideosApi::delete_chapters`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteChaptersParams {
    /// Video ID
    pub video_id: String
}

/// struct for passing parameters to the method [`VideosApi::delete_subtitle`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteSubtitleParams {
    /// Video ID
    pub video_id: String,
    /// Subtitle ID
    pub subtitle_id: String
}

/// struct for passing parameters to the method [`VideosApi::delete_subtitle_by_language`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteSubtitleByLanguageParams {
    /// Video ID
    pub video_id: String,
    /// Language Code (BCP 47)
    pub lang_code: String
}

/// struct for passing parameters to the method [`VideosApi::delete_subtitles`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteSubtitlesParams {
    /// Video ID
    pub video_id: String
}

/// struct for passing parameters to the method [`VideosApi::get`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetParams {
    /// Video ID
    pub video_id: String
}

/// struct for passing parameters to the method [`VideosApi::list`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct ListParams {
    /// Maximum number of items to return in a single request. <br> **Default:** `25`
    pub limit: Option<i32>,
    /// Starting point of the result set. <br>To get page 2 with a limit of 25, set `offset` to `25`. <br> **Default:** `0`
    pub offset: Option<i32>,
    /// Field to sort by (created_at, name, size, updated_at, duration)
    pub sort: Option<String>,
    /// Sort order (asc, desc)
    pub order: Option<String>
}

/// struct for passing parameters to the method [`VideosApi::replace_audio_tracks`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct ReplaceAudioTracksParams {
    /// Video ID
    pub video_id: String,
    /// Audio files (.mp3, .opus, .flac, .wav, .ac3, .m4a, .aac)
    pub files: Vec<std::path::PathBuf>,
    /// Comma-separated labels
    pub labels: String,
    /// Comma-separated language codes
    pub language_codes: String
}

/// struct for passing parameters to the method [`VideosApi::replace_subtitles`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct ReplaceSubtitlesParams {
    /// Video ID
    pub video_id: String,
    /// Subtitle files (.srt or .vtt)
    pub files: Vec<std::path::PathBuf>,
    /// Comma-separated labels
    pub labels: String,
    /// Comma-separated language codes
    pub language_codes: String
}

/// struct for passing parameters to the method [`VideosApi::update_audio_track_by_language`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct UpdateAudioTrackByLanguageParams {
    /// Video ID
    pub video_id: String,
    /// Language Code (BCP 47)
    pub lang_code: String,
    /// Audio file (.mp3, .opus, .flac, .wav, .ac3, .m4a, .aac)
    pub file: std::path::PathBuf,
    /// Label (e.g. English)
    pub label: Option<String>
}

/// struct for passing parameters to the method [`VideosApi::update_chapters`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct UpdateChaptersParams {
    /// Video ID
    pub video_id: String,
    /// Chapters array
    pub update_chapters_request: models::UpdateChaptersRequest
}

/// struct for passing parameters to the method [`VideosApi::update_subtitle_by_language`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct UpdateSubtitleByLanguageParams {
    /// Video ID
    pub video_id: String,
    /// Language Code (BCP 47)
    pub lang_code: String,
    /// Subtitle file (.srt or .vtt)
    pub file: std::path::PathBuf,
    /// Label (e.g. English)
    pub label: Option<String>
}

/// struct for passing parameters to the method [`VideosApi::update_thumbnail`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct UpdateThumbnailParams {
    /// Video ID
    pub video_id: String,
    /// Thumbnail image file (max 5MB, image/_*)
    pub thumbnail: std::path::PathBuf
}

/// struct for passing parameters to the method [`VideosApi::upload_complete`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct UploadCompleteParams {
    /// Video upload completion request
    pub video_upload_complete_request: models::VideoUploadCompleteRequest
}

/// struct for passing parameters to the method [`VideosApi::upload_init`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct UploadInitParams {
    /// Video upload initialization request
    pub video_upload_init_request: models::VideoUploadInitRequest
}


#[async_trait]
impl VideosApi for VideosApiClient {
    /// Delete a video by its ID within a project
    async fn delete(&self,  params: DeleteParams ) -> Result<(), Error<DeleteError>> {
        
        let DeleteParams {
            video_id,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/{videoId}/delete", local_var_configuration.base_path, videoId=crate::apis::urlencode(video_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<DeleteError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Remove an additional audio track from a video using API key authentication
    async fn delete_audio_track(&self,  params: DeleteAudioTrackParams ) -> Result<models::AudioTrackDelete, Error<DeleteAudioTrackError>> {
        
        let DeleteAudioTrackParams {
            video_id,
            track_id,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/{videoId}/audio-tracks/{trackId}", local_var_configuration.base_path, videoId=crate::apis::urlencode(video_id), trackId=crate::apis::urlencode(track_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AudioTrackDelete`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AudioTrackDelete`")))),
            }
        } else {
            let local_var_entity: Option<DeleteAudioTrackError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Remove an audio track for a specific language using API key authentication
    async fn delete_audio_track_by_language(&self,  params: DeleteAudioTrackByLanguageParams ) -> Result<models::AudioTrackDelete, Error<DeleteAudioTrackByLanguageError>> {
        
        let DeleteAudioTrackByLanguageParams {
            video_id,
            lang_code,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/{videoId}/audio-tracks/language/{lang_code}", local_var_configuration.base_path, videoId=crate::apis::urlencode(video_id), lang_code=crate::apis::urlencode(lang_code));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AudioTrackDelete`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AudioTrackDelete`")))),
            }
        } else {
            let local_var_entity: Option<DeleteAudioTrackByLanguageError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Remove all additional audio tracks from a video using API key authentication
    async fn delete_audio_tracks(&self,  params: DeleteAudioTracksParams ) -> Result<models::AudioTrackDelete, Error<DeleteAudioTracksError>> {
        
        let DeleteAudioTracksParams {
            video_id,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/{videoId}/audio-tracks", local_var_configuration.base_path, videoId=crate::apis::urlencode(video_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AudioTrackDelete`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AudioTrackDelete`")))),
            }
        } else {
            let local_var_entity: Option<DeleteAudioTracksError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Remove all chapters from a video using API key authentication
    async fn delete_chapters(&self,  params: DeleteChaptersParams ) -> Result<models::UpdateChaptersResponse, Error<DeleteChaptersError>> {
        
        let DeleteChaptersParams {
            video_id,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/{videoId}/chapters", local_var_configuration.base_path, videoId=crate::apis::urlencode(video_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateChaptersResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::UpdateChaptersResponse`")))),
            }
        } else {
            let local_var_entity: Option<DeleteChaptersError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Remove a subtitle from a video using API key authentication
    async fn delete_subtitle(&self,  params: DeleteSubtitleParams ) -> Result<models::SubtitleDelete, Error<DeleteSubtitleError>> {
        
        let DeleteSubtitleParams {
            video_id,
            subtitle_id,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/{videoId}/subtitles/{subtitleId}", local_var_configuration.base_path, videoId=crate::apis::urlencode(video_id), subtitleId=crate::apis::urlencode(subtitle_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SubtitleDelete`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::SubtitleDelete`")))),
            }
        } else {
            let local_var_entity: Option<DeleteSubtitleError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Remove a subtitle for a specific language using API key authentication
    async fn delete_subtitle_by_language(&self,  params: DeleteSubtitleByLanguageParams ) -> Result<models::SubtitleDelete, Error<DeleteSubtitleByLanguageError>> {
        
        let DeleteSubtitleByLanguageParams {
            video_id,
            lang_code,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/{videoId}/subtitles/language/{lang_code}", local_var_configuration.base_path, videoId=crate::apis::urlencode(video_id), lang_code=crate::apis::urlencode(lang_code));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SubtitleDelete`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::SubtitleDelete`")))),
            }
        } else {
            let local_var_entity: Option<DeleteSubtitleByLanguageError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Remove all subtitles from a video using API key authentication
    async fn delete_subtitles(&self,  params: DeleteSubtitlesParams ) -> Result<models::SubtitleDelete, Error<DeleteSubtitlesError>> {
        
        let DeleteSubtitlesParams {
            video_id,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/{videoId}/subtitles", local_var_configuration.base_path, videoId=crate::apis::urlencode(video_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SubtitleDelete`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::SubtitleDelete`")))),
            }
        } else {
            let local_var_entity: Option<DeleteSubtitlesError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieve a video by its ID for a specific project.
    async fn get(&self,  params: GetParams ) -> Result<models::Video, Error<GetError>> {
        
        let GetParams {
            video_id,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/{videoId}", local_var_configuration.base_path, videoId=crate::apis::urlencode(video_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Video`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Video`")))),
            }
        } else {
            let local_var_entity: Option<GetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieve all videos for a specific project, with pagination and sorting.
    async fn list(&self,  params: ListParams ) -> Result<models::PaginationPaginatedResponseVideo, Error<ListError>> {
        
        let ListParams {
            limit,
            offset,
            sort,
            order,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = limit {
            local_var_req_builder = local_var_req_builder.query(&[("limit", &param_value.to_string())]);
        }
        if let Some(ref param_value) = offset {
            local_var_req_builder = local_var_req_builder.query(&[("offset", &param_value.to_string())]);
        }
        if let Some(ref param_value) = sort {
            local_var_req_builder = local_var_req_builder.query(&[("sort", &param_value.to_string())]);
        }
        if let Some(ref param_value) = order {
            local_var_req_builder = local_var_req_builder.query(&[("order", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PaginationPaginatedResponseVideo`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::PaginationPaginatedResponseVideo`")))),
            }
        } else {
            let local_var_entity: Option<ListError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Get list of supported languages for subtitles
    async fn list_languages(&self, ) -> Result<Vec<models::SubtitleLanguageResponse>, Error<ListLanguagesError>> {
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/languages", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::SubtitleLanguageResponse&gt;`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `Vec&lt;models::SubtitleLanguageResponse&gt;`")))),
            }
        } else {
            let local_var_entity: Option<ListLanguagesError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Replace all audio tracks with the provided ones using API key authentication
    async fn replace_audio_tracks(&self,  params: ReplaceAudioTracksParams ) -> Result<Vec<models::AudioTrack>, Error<ReplaceAudioTracksError>> {
        
        let ReplaceAudioTracksParams {
            video_id,
            files,
            labels,
            language_codes,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/{videoId}/audio-tracks", local_var_configuration.base_path, videoId=crate::apis::urlencode(video_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };
        let mut local_var_form = reqwest::multipart::Form::new();
        for path in &files {
            local_var_form = local_var_form.file("files", path.as_os_str()).await?;
        }
        local_var_form = local_var_form.text("labels", labels.to_string());
        local_var_form = local_var_form.text("language_codes", language_codes.to_string());
        local_var_req_builder = local_var_req_builder.multipart(local_var_form);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::AudioTrack&gt;`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `Vec&lt;models::AudioTrack&gt;`")))),
            }
        } else {
            let local_var_entity: Option<ReplaceAudioTracksError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Replace all subtitles with the provided ones using API key authentication
    async fn replace_subtitles(&self,  params: ReplaceSubtitlesParams ) -> Result<Vec<models::Subtitle>, Error<ReplaceSubtitlesError>> {
        
        let ReplaceSubtitlesParams {
            video_id,
            files,
            labels,
            language_codes,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/{videoId}/subtitles", local_var_configuration.base_path, videoId=crate::apis::urlencode(video_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };
        let mut local_var_form = reqwest::multipart::Form::new();
        for path in &files {
            local_var_form = local_var_form.file("files", path.as_os_str()).await?;
        }
        local_var_form = local_var_form.text("labels", labels.to_string());
        local_var_form = local_var_form.text("language_codes", language_codes.to_string());
        local_var_req_builder = local_var_req_builder.multipart(local_var_form);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Subtitle&gt;`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `Vec&lt;models::Subtitle&gt;`")))),
            }
        } else {
            let local_var_entity: Option<ReplaceSubtitlesError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Add or replace an audio track for a specific language using API key authentication
    async fn update_audio_track_by_language(&self,  params: UpdateAudioTrackByLanguageParams ) -> Result<models::AudioTrack, Error<UpdateAudioTrackByLanguageError>> {
        
        let UpdateAudioTrackByLanguageParams {
            video_id,
            lang_code,
            file,
            label,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/{videoId}/audio-tracks/language/{lang_code}", local_var_configuration.base_path, videoId=crate::apis::urlencode(video_id), lang_code=crate::apis::urlencode(lang_code));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };
        let mut local_var_form = reqwest::multipart::Form::new();
        local_var_form = local_var_form.file("file", file.as_os_str()).await?;
        if let Some(local_var_param_value) = label {
            local_var_form = local_var_form.text("label", local_var_param_value.to_string());
        }
        local_var_req_builder = local_var_req_builder.multipart(local_var_form);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AudioTrack`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AudioTrack`")))),
            }
        } else {
            let local_var_entity: Option<UpdateAudioTrackByLanguageError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Replace all chapters for a video (atomic PUT operation) using API key authentication
    async fn update_chapters(&self,  params: UpdateChaptersParams ) -> Result<models::UpdateChaptersResponse, Error<UpdateChaptersError>> {
        
        let UpdateChaptersParams {
            video_id,
            update_chapters_request,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/{videoId}/chapters", local_var_configuration.base_path, videoId=crate::apis::urlencode(video_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&update_chapters_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateChaptersResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::UpdateChaptersResponse`")))),
            }
        } else {
            let local_var_entity: Option<UpdateChaptersError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Add or replace a subtitle for a specific language using API key authentication
    async fn update_subtitle_by_language(&self,  params: UpdateSubtitleByLanguageParams ) -> Result<models::Subtitle, Error<UpdateSubtitleByLanguageError>> {
        
        let UpdateSubtitleByLanguageParams {
            video_id,
            lang_code,
            file,
            label,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/{videoId}/subtitles/language/{lang_code}", local_var_configuration.base_path, videoId=crate::apis::urlencode(video_id), lang_code=crate::apis::urlencode(lang_code));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };
        let mut local_var_form = reqwest::multipart::Form::new();
        local_var_form = local_var_form.file("file", file.as_os_str()).await?;
        if let Some(local_var_param_value) = label {
            local_var_form = local_var_form.text("label", local_var_param_value.to_string());
        }
        local_var_req_builder = local_var_req_builder.multipart(local_var_form);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Subtitle`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Subtitle`")))),
            }
        } else {
            let local_var_entity: Option<UpdateSubtitleByLanguageError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Update the thumbnail image for an existing video using API key authentication
    async fn update_thumbnail(&self,  params: UpdateThumbnailParams ) -> Result<models::Video, Error<UpdateThumbnailError>> {
        
        let UpdateThumbnailParams {
            video_id,
            thumbnail,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/{videoId}/thumbnail", local_var_configuration.base_path, videoId=crate::apis::urlencode(video_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };
        let mut local_var_form = reqwest::multipart::Form::new();
        local_var_form = local_var_form.file("thumbnail", thumbnail.as_os_str()).await?;
        local_var_req_builder = local_var_req_builder.multipart(local_var_form);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Video`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Video`")))),
            }
        } else {
            let local_var_entity: Option<UpdateThumbnailError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Mark a video upload as complete after successful upload to storage using API key authentication
    async fn upload_complete(&self,  params: UploadCompleteParams ) -> Result<models::Video, Error<UploadCompleteError>> {
        
        let UploadCompleteParams {
            video_upload_complete_request,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/upload/complete", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&video_upload_complete_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Video`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Video`")))),
            }
        } else {
            let local_var_entity: Option<UploadCompleteError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Initialize a video upload and get presigned URLs for video and poster using API key authentication
    async fn upload_init(&self,  params: UploadInitParams ) -> Result<models::VideoUploadInitResponse, Error<UploadInitError>> {
        
        let UploadInitParams {
            video_upload_init_request,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/videos/upload/init", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-Key", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&video_upload_init_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::VideoUploadInitResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::VideoUploadInitResponse`")))),
            }
        } else {
            let local_var_entity: Option<UploadInitError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`VideosApi::delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteError {
    Status400(models::ErrorResponse),
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    Status404(models::ErrorResponse),
    Status500(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::delete_audio_track`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAudioTrackError {
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    Status404(models::ErrorResponse),
    Status500(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::delete_audio_track_by_language`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAudioTrackByLanguageError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::delete_audio_tracks`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAudioTracksError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::delete_chapters`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteChaptersError {
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    Status404(models::ErrorResponse),
    Status500(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::delete_subtitle`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteSubtitleError {
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    Status404(models::ErrorResponse),
    Status500(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::delete_subtitle_by_language`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteSubtitleByLanguageError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::delete_subtitles`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteSubtitlesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetError {
    Status400(models::ErrorResponse),
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    Status404(models::ErrorResponse),
    Status500(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::list`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListError {
    Status400(models::ErrorResponse),
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    Status500(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::list_languages`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListLanguagesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::replace_audio_tracks`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReplaceAudioTracksError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::replace_subtitles`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReplaceSubtitlesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::update_audio_track_by_language`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateAudioTrackByLanguageError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::update_chapters`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateChaptersError {
    Status400(models::ErrorResponse),
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    Status404(models::ErrorResponse),
    Status500(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::update_subtitle_by_language`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateSubtitleByLanguageError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::update_thumbnail`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateThumbnailError {
    Status400(models::ErrorResponse),
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    Status404(models::ErrorResponse),
    Status500(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::upload_complete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UploadCompleteError {
    Status400(models::ErrorResponse),
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    Status404(models::ErrorResponse),
    Status500(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`VideosApi::upload_init`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UploadInitError {
    Status400(models::ErrorResponse),
    Status401(models::ErrorResponse),
    Status403(models::ErrorResponse),
    Status500(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

