[package]
name = "rixl"
version = "0.1.0"
authors = ["support@rixl.com"]
description = "**Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale."
license = "All Rights Reserved"
edition = "2021"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
serde_repr = "^0.1"
url = "^2.5"
async-trait = "^0.1"
reqwest = { version = "^0.13", default-features = false, features = ["json", "multipart", "stream", "query", "form"] }
bon = { version = "2.3", optional = true }
[features]
default = ["native-tls", "bon"]
native-tls = ["reqwest/native-tls"]
rustls = ["reqwest/rustls"]
bon = ["dep:bon"]
