/*
 * RIXL API
 *
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VideoResponse {
    #[serde(rename = "bitrate", skip_serializing_if = "Option::is_none")]
    pub bitrate: Option<i32>,
    #[serde(rename = "chapters", skip_serializing_if = "Option::is_none")]
    pub chapters: Option<Vec<models::Chapter>>,
    #[serde(rename = "codec", skip_serializing_if = "Option::is_none")]
    pub codec: Option<String>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<Box<models::File>>,
    #[serde(rename = "framerate", skip_serializing_if = "Option::is_none")]
    pub framerate: Option<String>,
    #[serde(rename = "hdr", skip_serializing_if = "Option::is_none")]
    pub hdr: Option<bool>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "plan_type", skip_serializing_if = "Option::is_none")]
    pub plan_type: Option<models::PlanType>,
    #[serde(rename = "poster", skip_serializing_if = "Option::is_none")]
    pub poster: Option<Box<models::Image>>,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
}

impl VideoResponse {
    pub fn new() -> VideoResponse {
        VideoResponse {
            bitrate: None,
            chapters: None,
            codec: None,
            duration: None,
            file: None,
            framerate: None,
            hdr: None,
            height: None,
            id: None,
            plan_type: None,
            poster: None,
            width: None,
        }
    }
}

