/*
 * RIXL API
 *
 * **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@rixl.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VideoUploadInitResponse {
    #[serde(rename = "poster_id", skip_serializing_if = "Option::is_none")]
    pub poster_id: Option<String>,
    #[serde(rename = "poster_presigned_url", skip_serializing_if = "Option::is_none")]
    pub poster_presigned_url: Option<String>,
    #[serde(rename = "upload_expires", skip_serializing_if = "Option::is_none")]
    pub upload_expires: Option<i32>,
    #[serde(rename = "video_id", skip_serializing_if = "Option::is_none")]
    pub video_id: Option<String>,
    #[serde(rename = "video_presigned_url", skip_serializing_if = "Option::is_none")]
    pub video_presigned_url: Option<String>,
}

impl VideoUploadInitResponse {
    pub fn new() -> VideoUploadInitResponse {
        VideoUploadInitResponse {
            poster_id: None,
            poster_presigned_url: None,
            upload_expires: None,
            video_id: None,
            video_presigned_url: None,
        }
    }
}

